# Generated by Django 5.0.3 on 2024-09-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.CharField(choices=[('Flood', 'Flood'), ('Earthquake', 'Earthquake'), ('Cyclone', 'Cyclone'), ('Landslide', 'Landslide'), ('Tsunami', 'Tsunami')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('data', models.TextField()),
            ],
        ),
    ]
