# Generated by Django 5.0.3 on 2024-09-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='disaster_type',
            field=models.CharField(choices=[('Flood', 'Flood'), ('Earthquake', 'Earthquake'), ('Cyclone', 'Cyclone'), ('Landslide', 'Landslide'), ('Tsunami', 'Tsunami'), ('Storm', 'Storm'), ('Drought', 'Drought'), ('Epidemic', 'Epidemic')], max_length=50),
        ),
    ]
